- name: install nginx server
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: enable and start nginx
  # tags:
  # - restart_nginx_service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: common roles
  tags: 
  - tags-practice
  include_role:
    name: common
    tasks_from: main


- name: copy expense config
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart Nginx

